services:
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: akfm_redis
    volumes:
      - akfm-redis:/data
    restart: always
  redis-stack:
    image: redis/redis-stack:latest
    container_name: cache-handler-redis
    ports:
      - 7001:6379
      - 8001:8001
volumes:
  akfm-redis:
    driver: local