services:
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: akfm_laboratory_redis_session
    volumes:
      - akfm-laboratory-session-redis:/data
    restart: always
  redis-stack:
    image: redis/redis-stack:latest
    container_name: akfm_laboratory_redis_cache_handler
    ports:
      - 7001:6379
      - 8001:8001
  db_development:
    image: postgres:15.3-alpine
    container_name: akfm_laboratory_postgres_core_development
    ports:
      - 5432:5432
    volumes:
      - akfm-laboratory-core-db-development-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=akfm_laboratory_core_development
      - POSTGRES_USER=akfm
      - POSTGRES_PASSWORD=akfm
  db_test:
    image: postgres:15.3-alpine
    container_name: akfm_laboratory_postgres_core_test
    ports:
      - 5433:5432
    volumes:
      - akfm-laboratory-core-db-test-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=akfm_laboratory_core_test
      - POSTGRES_USER=akfm
      - POSTGRES_PASSWORD=akfm
  mailer:
    image: mailtutan/mailtutan:latest
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  akfm-laboratory-session-redis:
    driver: local
  akfm-laboratory-core-db-development-store:
  akfm-laboratory-core-db-test-store: