#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm run check

cargo fmt --check --manifest-path backend/core/Cargo.toml
cargo clippy --manifest-path backend/core/Cargo.toml --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery -W rust-2018-idioms
